library(magrittr)
library(tidyverse)

preprocessNewData = function() {
  initDir = getwd()
  setwd(WORKING_DIR)
  newRes = readLines("NewlyFoundPapers")
  newRes = newRes[newRes != '']
  newRes %<>% str_remove_all("\t") %>% 
    str_remove_all("https://") %>%
    str_remove_all("sequences") %>%
    str_trim() %>%
    str_split_fixed(" ", 5)
  newRes = newRes %>%
    set_colnames(c("URL", "Size", "Genus", "Species", "Context")) %>%
    as_tibble() %>%
    mutate_at("URL", ~str_sub(., 1, -2))
  newRes = newRes %>%
    mutate_at("Size", as.integer) %>%
    mutate_at("Context", ~{badPos = which(nchar(.) == 0); .[badPos] = "human"; .})
  newRes %<>% arrange(Species, -Size) %>%
    mutate(GenoData = NA) %>%
    mutate(PhenoData = NA) %>%
    mutate(UpdatedSize = Size) %>%
    mutate_if(is.character, ~{str_trim(.)}) %>%
    mutate_at("Context", ~{badPos = which(str_sub(.,1,1) == "[" & str_sub(.,-1,-1) == "]");
      .[badPos] = str_sub(.[badPos], 2, -2); .})
  write_csv(newRes, "NewlyFoundPapers.csv")
  ### PLEASE START EDITING FROM HERE! ###
  newRes$GenoData[1]
  newRes$PhenoData[1] = newRes$GenoData[1]
  newRes$GenoData[2]
  newRes$PhenoData[2] = newRes$GenoData[2]
  newRes$GenoData[3]
  newRes$PhenoData[3] = newRes$GenoData[3]
  newRes$GenoData[4]
  newRes$PhenoData[4] = newRes$GenoData[4]
  newRes$GenoData[5]
  newRes$PhenoData[5] = newRes$GenoData[5]
  newRes$GenoData[6]
  newRes$PhenoData[6] = newRes$GenoData[6]
  newRes$GenoData[7]
  newRes$PhenoData[7] = newRes$GenoData[7]
  newRes$GenoData[8]
  newRes$PhenoData[8] = newRes$GenoData[8]
  newRes$GenoData[9]
  newRes$PhenoData[9] = newRes$GenoData[9]
  newRes$GenoData[10]
  newRes$PhenoData[10] = newRes$GenoData[10]
  newRes$GenoData[11]
  newRes$PhenoData[11] = newRes$GenoData[11]
  newRes$GenoData[12]
  newRes$PhenoData[12] = newRes$GenoData[12]
  newRes$GenoData[13]
  newRes$PhenoData[13] = newRes$GenoData[13]
  newRes$GenoData[14]
  newRes$PhenoData[14] = newRes$GenoData[14]
  newRes$GenoData[15]
  newRes$PhenoData[15] = newRes$GenoData[15]
  newRes$GenoData[16]
  newRes$PhenoData[16] = newRes$GenoData[16]
  newRes$GenoData[17]
  newRes$PhenoData[17] = newRes$GenoData[17]
  newRes$GenoData[18]
  newRes$PhenoData[18] = newRes$GenoData[18]
  newRes$GenoData[19]
  newRes$PhenoData[19] = newRes$GenoData[19]
  newRes$GenoData[20]
  newRes$PhenoData[20] = newRes$GenoData[20]
  newRes$GenoData[21]
  newRes$PhenoData[21] = newRes$GenoData[21]
  newRes$GenoData[22]
  newRes$PhenoData[22] = newRes$GenoData[22]
  newRes$GenoData[23]
  newRes$PhenoData[23] = newRes$GenoData[23]
  newRes$GenoData[24]
  newRes$PhenoData[24] = newRes$GenoData[24]
  newRes$GenoData[25]
  newRes$PhenoData[25] = newRes$GenoData[25]
  newRes$GenoData[26]
  newRes$PhenoData[26] = newRes$GenoData[26]
  newRes$GenoData[27]
  newRes$PhenoData[27] = newRes$GenoData[27]
  newRes$GenoData[28]
  newRes$PhenoData[28] = newRes$GenoData[28]
  newRes$GenoData[29]
  newRes$PhenoData[29] = newRes$GenoData[29]
  newRes$GenoData[30]
  newRes$PhenoData[30] = newRes$GenoData[30]
  newRes$GenoData[31]
  newRes$PhenoData[31] = newRes$GenoData[31]
  newRes$GenoData[32]
  newRes$PhenoData[32] = newRes$GenoData[32]
  newRes$GenoData[33]
  newRes$PhenoData[33] = newRes$GenoData[33]
  newRes$GenoData[34]
  newRes$PhenoData[34] = newRes$GenoData[34]
  newRes$GenoData[35]
  newRes$PhenoData[35] = newRes$GenoData[35]
  newRes$GenoData[36]
  newRes$PhenoData[36] = newRes$GenoData[36]
  newRes$GenoData[37]
  newRes$PhenoData[37] = newRes$GenoData[37]
  newRes$GenoData[38]
  newRes$PhenoData[38] = newRes$GenoData[38]
  newRes$GenoData[39]
  newRes$PhenoData[39] = newRes$GenoData[39]
  newRes$GenoData[40]
  newRes$PhenoData[40] = newRes$GenoData[40]
  newRes$GenoData[41]
  newRes$PhenoData[41] = newRes$GenoData[41]
  newRes$GenoData[42]
  newRes$PhenoData[42] = newRes$GenoData[42]
  newRes$GenoData[43]
  newRes$PhenoData[43] = newRes$GenoData[43]
  newRes$GenoData[44]
  newRes$PhenoData[44] = newRes$GenoData[44]
  newRes$GenoData[45]
  newRes$PhenoData[45] = newRes$GenoData[45]
  newRes$GenoData[46]
  newRes$PhenoData[46] = newRes$GenoData[46]
  newRes$GenoData[47]
  newRes$PhenoData[47] = newRes$GenoData[47]
  newRes$GenoData[48]
  newRes$PhenoData[48] = newRes$GenoData[48]
  newRes$GenoData[49]
  newRes$PhenoData[49] = newRes$GenoData[49]
  newRes$GenoData[50]
  newRes$PhenoData[50] = newRes$GenoData[50]
  newRes$GenoData[51]
  newRes$PhenoData[51] = newRes$GenoData[51]
  newRes$GenoData[52]
  newRes$PhenoData[52] = newRes$GenoData[52]
  newRes$GenoData[53]
  newRes$PhenoData[53] = newRes$GenoData[53]
  newRes$GenoData[54]
  newRes$PhenoData[54] = newRes$GenoData[54]
  newRes$GenoData[55]
  newRes$PhenoData[55] = newRes$GenoData[55]
  newRes$GenoData[56]
  newRes$PhenoData[56] = newRes$GenoData[56]
  newRes$GenoData[57]
  newRes$PhenoData[57] = newRes$GenoData[57]
  newRes$GenoData[58]
  newRes$PhenoData[58] = newRes$GenoData[58]
  newRes$GenoData[59]
  newRes$PhenoData[59] = newRes$GenoData[59]
  newRes$GenoData[60]
  newRes$PhenoData[60] = newRes$GenoData[60]
  newRes$GenoData[61]
  newRes$PhenoData[61] = newRes$GenoData[61]
  newRes$GenoData[62]
  newRes$PhenoData[62] = newRes$GenoData[62]
  newRes$GenoData[63]
  newRes$PhenoData[63] = newRes$GenoData[63]
  newRes$GenoData[64]
  newRes$PhenoData[64] = newRes$GenoData[64]
  newRes$GenoData[65]
  newRes$PhenoData[65] = newRes$GenoData[65]
  newRes$GenoData[66]
  newRes$PhenoData[66] = newRes$GenoData[66]
  newRes$GenoData[67]
  newRes$PhenoData[67] = newRes$GenoData[67]
  newRes$GenoData[68]
  newRes$PhenoData[68] = newRes$GenoData[68]
  newRes$GenoData[69]
  newRes$PhenoData[69] = newRes$GenoData[69]
  newRes$GenoData[70]
  newRes$PhenoData[70] = newRes$GenoData[70]
  newRes$GenoData[71]
  newRes$PhenoData[71] = newRes$GenoData[71]
  newRes$GenoData[72]
  newRes$PhenoData[72] = newRes$GenoData[72]
  newRes$GenoData[73]
  newRes$PhenoData[73] = newRes$GenoData[73]
  newRes$GenoData[74]
  newRes$PhenoData[74] = newRes$GenoData[74]
  newRes$GenoData[75]
  newRes$PhenoData[75] = newRes$GenoData[75]
  newRes$GenoData[76]
  newRes$PhenoData[76] = newRes$GenoData[76]
  newRes$GenoData[77]
  newRes$PhenoData[77] = newRes$GenoData[77]
  newRes$GenoData[78]
  newRes$PhenoData[78] = newRes$GenoData[78]
  newRes$GenoData[79]
  newRes$PhenoData[79] = newRes$GenoData[79]
  newRes$GenoData[80]
  newRes$PhenoData[80] = newRes$GenoData[80]
  newRes$GenoData[81]
  newRes$PhenoData[81] = newRes$GenoData[81]
  newRes$GenoData[82]
  newRes$PhenoData[82] = newRes$GenoData[82]
  newRes$GenoData[83]
  newRes$PhenoData[83] = newRes$GenoData[83]
  newRes$GenoData[84]
  newRes$PhenoData[84] = newRes$GenoData[84]
  newRes$GenoData[85]
  newRes$PhenoData[85] = newRes$GenoData[85]
  newRes$GenoData[86]
  newRes$PhenoData[86] = newRes$GenoData[86]
  newRes$GenoData[87]
  newRes$PhenoData[87] = newRes$GenoData[87]
  newRes$GenoData[88]
  newRes$PhenoData[88] = newRes$GenoData[88]
  newRes$GenoData[89]
  newRes$PhenoData[89] = newRes$GenoData[89]
  newRes$GenoData[90]
  newRes$PhenoData[90] = newRes$GenoData[90]
  newRes$GenoData[91]
  newRes$PhenoData[91] = newRes$GenoData[91]
  newRes$GenoData[92]
  newRes$PhenoData[92] = newRes$GenoData[92]
  newRes$GenoData[93]
  newRes$PhenoData[93] = newRes$GenoData[93]
  newRes$GenoData[94]
  newRes$PhenoData[94] = newRes$GenoData[94]
  newRes$GenoData[95]
  newRes$PhenoData[95] = newRes$GenoData[95]
  newRes$GenoData[96]
  newRes$PhenoData[96] = newRes$GenoData[96]
  newRes$GenoData[97]
  newRes$PhenoData[97] = newRes$GenoData[97]
  newRes$GenoData[98]
  newRes$PhenoData[98] = newRes$GenoData[98]
  newRes$GenoData[99]
  newRes$PhenoData[99] = newRes$GenoData[99]
  newRes$GenoData[100]
  newRes$PhenoData[100] = newRes$GenoData[100]
  newRes$GenoData[101]
  newRes$PhenoData[101] = newRes$GenoData[101]
  newRes$GenoData[102]
  newRes$PhenoData[102] = newRes$GenoData[102]
  newRes$GenoData[103]
  newRes$PhenoData[103] = newRes$GenoData[103]
  newRes$GenoData[104]
  newRes$PhenoData[104] = newRes$GenoData[104]
  newRes$GenoData[105]
  newRes$PhenoData[105] = newRes$GenoData[105]
  newRes$GenoData[106]
  newRes$PhenoData[106] = newRes$GenoData[106]
  newRes$GenoData[107]
  newRes$PhenoData[107] = newRes$GenoData[107]
  newRes$GenoData[108]
  newRes$PhenoData[108] = newRes$GenoData[108]
  newRes$GenoData[109]
  newRes$PhenoData[109] = newRes$GenoData[109]
  newRes$GenoData[110]
  newRes$PhenoData[110] = newRes$GenoData[110]
  newRes$GenoData[111]
  newRes$PhenoData[111] = newRes$GenoData[111]
  newRes$GenoData[112]
  newRes$PhenoData[112] = newRes$GenoData[112]
  newRes$GenoData[113]
  newRes$PhenoData[113] = newRes$GenoData[113]
  newRes$GenoData[114]
  newRes$PhenoData[114] = newRes$GenoData[114]
  newRes$GenoData[115]
  newRes$PhenoData[115] = newRes$GenoData[115]
  newRes$GenoData[116]
  newRes$PhenoData[116] = newRes$GenoData[116]
  newRes$GenoData[117]
  newRes$PhenoData[117] = newRes$GenoData[117]
  newRes$GenoData[118]
  newRes$PhenoData[118] = newRes$GenoData[118]
  newRes$GenoData[119]
  newRes$PhenoData[119] = newRes$GenoData[119]
  newRes$GenoData[120]
  newRes$PhenoData[120] = newRes$GenoData[120]
  newRes$GenoData[121]
  newRes$PhenoData[121] = newRes$GenoData[121]
  newRes$GenoData[122]
  newRes$PhenoData[122] = newRes$GenoData[122]
  newRes$GenoData[123]
  newRes$PhenoData[123] = newRes$GenoData[123]
  newRes$GenoData[124]
  newRes$PhenoData[124] = newRes$GenoData[124]
  newRes$GenoData[125]
  newRes$PhenoData[125] = newRes$GenoData[125]
  newRes$GenoData[126]
  newRes$PhenoData[126] = newRes$GenoData[126]
  newRes$GenoData[127]
  newRes$PhenoData[127] = newRes$GenoData[127]
  newRes$GenoData[128]
  newRes$PhenoData[128] = newRes$GenoData[128]
  newRes$GenoData[129]
  newRes$PhenoData[129] = newRes$GenoData[129]
  newRes$GenoData[130]
  newRes$PhenoData[130] = newRes$GenoData[130]
  newRes$GenoData[131]
  newRes$PhenoData[131] = newRes$GenoData[131]
  newRes$GenoData[132]
  newRes$PhenoData[132] = newRes$GenoData[132]
  newRes$GenoData[133]
  newRes$PhenoData[133] = newRes$GenoData[133]
  newRes$GenoData[134]
  newRes$PhenoData[134] = newRes$GenoData[134]
  newRes$GenoData[135]
  newRes$PhenoData[135] = newRes$GenoData[135]
  newRes$GenoData[136]
  newRes$PhenoData[136] = newRes$GenoData[136]
  newRes$GenoData[137]
  newRes$PhenoData[137] = newRes$GenoData[137]
  newRes$GenoData[138]
  newRes$PhenoData[138] = newRes$GenoData[138]
  newRes$GenoData[139]
  newRes$PhenoData[139] = newRes$GenoData[139]
  newRes$GenoData[140]
  newRes$PhenoData[140] = newRes$GenoData[140]
  newRes$GenoData[141]
  newRes$PhenoData[141] = newRes$GenoData[141]
  newRes$GenoData[142]
  newRes$PhenoData[142] = newRes$GenoData[142]
  newRes$GenoData[143]
  newRes$PhenoData[143] = newRes$GenoData[143]
  newRes$GenoData[144]
  newRes$PhenoData[144] = newRes$GenoData[144]
  newRes$GenoData[145]
  newRes$PhenoData[145] = newRes$GenoData[145]
  newRes$GenoData[146]
  newRes$PhenoData[146] = newRes$GenoData[146]
  newRes$GenoData[147]
  newRes$PhenoData[147] = newRes$GenoData[147]
  newRes$GenoData[148]
  newRes$PhenoData[148] = newRes$GenoData[148]
  newRes$GenoData[149]
  newRes$PhenoData[149] = newRes$GenoData[149]
  newRes$GenoData[150]
  newRes$PhenoData[150] = newRes$GenoData[150]
  newRes$GenoData[151]
  newRes$PhenoData[151] = newRes$GenoData[151]
  newRes$GenoData[152]
  newRes$PhenoData[152] = newRes$GenoData[152]
  newRes$GenoData[153]
  newRes$PhenoData[153] = newRes$GenoData[153]
  newRes$GenoData[154]
  newRes$PhenoData[154] = newRes$GenoData[154]
  newRes$GenoData[155]
  newRes$PhenoData[155] = newRes$GenoData[155]
  newRes$GenoData[156]
  newRes$PhenoData[156] = newRes$GenoData[156]
  newRes$GenoData[157]
  newRes$PhenoData[157] = newRes$GenoData[157]
  newRes$GenoData[158]
  newRes$PhenoData[158] = newRes$GenoData[158]
  newRes$GenoData[159]
  newRes$PhenoData[159] = newRes$GenoData[159]
  newRes$GenoData[160]
  newRes$PhenoData[160] = newRes$GenoData[160]
  ### ONCE YOU ARE DONE, PLEASE USE THIS COMMAND ###
  setwd(initDir)
  write_csv(newRes, "NewlyFoundPapersWithDetails.csv")
}
